### ISSUE TITLE
Lizenzverweisgenerator unable to identify chosen CC-by-sa 3.0 license

### ISSUE THREAD

**Issue by MathiasSchindler** [wmde/Lizenzverweisgenerator#60]
https://commons.wikimedia.org/wiki/File:14-08-10-wikimania-gruppenfoto-01.jpg generates the error message "Leider wird die ermittelte Lizenz des Bildes von dieser Anwendung nicht unterstützt.", even if the license in place is CC-by-sa 3.0.

Has this something to do with the Austrian localisation of the license in this case?

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T105343
