### ISSUE TITLE
Doesn't recognize author's name

### ISSUE THREAD

**Issue by KatjaUllrich** [wmde/Lizenzverweisgenerator#62]
https://commons.wikimedia.org/wiki/File:Karl-Marx-Allee_Frankfurter_Tor_Turm_Schild.jpg
Tool claims that author is anonymous.

**Comment by tobijat** [comment]
See also https://phabricator.wikimedia.org/T105295

**Comment by tobijat** [comment]
moved to https://phabricator.wikimedia.org/T105347
