### ISSUE TITLE
Generated attribution links only http://

### ISSUE THREAD

**Issue by KatjaUllrich** [wmde/Lizenzverweisgenerator#63]

**Comment by KatjaUllrich** [comment]
also: broken links to creativecommons.org due to http://

**Comment by thiemowmde** [comment]
Can you please be more specific? What is wrong? What is the actual and the expected behavior?

**Comment by KatjaUllrich** [comment]
All the links used and generated by the pool are html://. Silke said that her browser even doesn't display "mixed content". Also, the links that refer to content located at creativecommons.org still uses and html://. These links don't work anymore since CC switched their website to https://. I think we just switch everything to https://. Does that make it clearer?

**Comment by tobijat** [comment]
see also https://phabricator.wikimedia.org/T105295
